### ISSUE TITLE
Unit 13 game issues with remaPSV

### ISSUE THREAD

**Issue by rand92000** [Rinnegatamante/remaPSV#19]
Unit 13 game becomes unresponsive (touch screen doesn't work after the intro logos) while remapsv.suprx is installed
I've found that the FIX is to uninstall remapsv.suprx and replace it with remapsv2.suprx

it is the issue anyways so I thought it's good to write an issue about it here. Just for you to know if you struggle with it too

Thanks, Rinnegatamante for this script anyways :)

**Comment by Rinnegatamante** [comment]
remaPSV is to be considered discontinued and superseeded by remaPSV2 indeed. For any further issue, report it to Mer1e on remaPSV2 repo.
