### ISSUE TITLE
PSTV not responding

### ISSUE THREAD

**Issue by holz-one** [Rinnegatamante/remaPSV#2]
Hello, I tried your plugin a few days ago on my PSTV and it appears no to respond in unit13.  I have enable touch screen controls enabled (push l3 for front, r3 for back, etc).  

Has this been tested on your end?  

I'll test the updated version and inform you about my results.  I'm on version 3.60 firmware

Thanks, this is great project idea

**Comment by Rinnegatamante** [comment]
The plugin has been tested only with some games (obviously) so it can actually have issues with some untested games.
What do you mean by "push l3 for front, r3 for back, etc"?
