### ISSUE TITLE
Menu isn't appeared in v1.1 on PSTV.

### ISSUE THREAD

**Issue by pettiagalla** [Rinnegatamante/remaPSV#3]
PSTV 3.65 Enso 
I tested with VitaShell and VA-11 Hall-A.
remaPSV menu is appears in v1.0, but not in v1.1 .

**Comment by cpenny1** [comment]
PSTV 3.60
Enso

It is happening to me too. I tried it with both Ratchet 2 and Duke Nukem Megaton Edition. The menu only works in 1.0.

**Comment by Rinnegatamante** [comment]
Try to redownload now the plugin and check if it works.

**Comment by cpenny1** [comment]
I will be able to test in a few mins. Thanks for the speedy reply. Do I download the plugin from that vitadb website?

**Comment by Rinnegatamante** [comment]
Yes.

**Comment by pettiagalla** [comment]
thanks! v1.1 menu is displayed.
